export class CaseService {
  static MAX_ALERTS = 5;

  constructor({ alertsUrl, incidentsUrl, casesUrl, rulesUrl } = {}) {
    this.urls = { alertsUrl, incidentsUrl, casesUrl, rulesUrl };
    this.alerts = [];
    this.incidents = [];
    this.cases = [];
    this.rules = [];
    this.liveFeed = [];
    this.subscribers = new Set();
    this.generatedAlertCounter = 9000;
  }

  async init() {
    const [alerts, incidents, cases, rules] = await Promise.all([
      this.#loadJson(this.urls.alertsUrl, []),
      this.#loadJson(this.urls.incidentsUrl, []),
      this.#loadJson(this.urls.casesUrl, []),
      this.#loadJson(this.urls.rulesUrl, []),
    ]);

    this.alerts = alerts;
    this.incidents = incidents;
    this.cases = cases;
    this.rules = rules;
    this.liveFeed = this.#buildInitialFeed();
  }

  getRules() {
    return this.rules.map((rule) => ({
      ...rule,
      alert_count: this.alerts.filter((alert) => alert.rule_id === rule.rule_id).length,
    }));
  }

  updateRule(ruleId, { summary, rule_code }) {
    const rule = this.rules.find((item) => item.rule_id === ruleId);
    if (!rule) return null;
    rule.summary = summary;
    rule.rule_code = rule_code;
    this.notify();
    return rule;
  }

  subscribe(fn) {
    this.subscribers.add(fn);
    return () => this.subscribers.delete(fn);
  }

  notify() {
    for (const fn of this.subscribers) fn();
  }

  getAlerts() {
    return this.alerts.map((alert) => this.#alertWithRule(alert));
  }

  getIncidents() {
    return this.incidents
      .map((incident) => this.#incidentWithRuntimeFields(incident))
      .sort((a, b) => new Date(b.created_date).getTime() - new Date(a.created_date).getTime());
  }

  getIncident(id) {
    const incident = this.incidents.find((item) => item.incident_id === id);
    return incident ? this.#incidentWithRuntimeFields(incident) : null;
  }

  getIncidentAlerts(incidentId) {
    const incident = this.incidents.find((item) => item.incident_id === incidentId);
    if (!incident) return [];
    return incident.alert_ids
      .map((alertId) => this.alerts.find((alert) => alert.alert_id === alertId))
      .map((alert) => this.#alertWithRule(alert))
      .filter(Boolean);
  }

  getCases() {
    return [...this.cases].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
  }

  getCaseByIncident(incidentId) {
    return this.cases.find((caseItem) => caseItem.linked_incident_id === incidentId) || null;
  }

  createCase(incidentId) {
    const incident = this.getIncident(incidentId);
    if (!incident) throw new Error(`Incident not found: ${incidentId}`);

    const existing = this.getCaseByIncident(incidentId);
    if (existing) return existing;

    const nextNumber = this.cases.length + 2401;
    const caseItem = {
      case_id: `CASE-${nextNumber}`,
      linked_incident_id: incidentId,
      status: 'In Progress',
      verdict: '',
      assigned_analyst: 'SOC Analyst L2',
      investigation_notes: '',
      created_at: new Date().toISOString(),
      closed_at: '',
    };

    this.cases.push(caseItem);
    this.notify();
    return caseItem;
  }

  updateCase(caseId, patch, { silent = false } = {}) {
    const caseItem = this.cases.find((item) => item.case_id === caseId);
    if (!caseItem) return null;
    Object.assign(caseItem, patch);
    if (!silent) this.notify();
    return caseItem;
  }

  closeCase(caseId) {
    return this.updateCase(caseId, {
      status: 'Closed',
      closed_at: new Date().toISOString(),
    });
  }

  escalateIncident(incidentId) {
    const incident = this.incidents.find((item) => item.incident_id === incidentId);
    if (!incident) return null;
    incident.escalated = true;
    this.notify();
    return incident;
  }

  addGeneratedAlert() {
    if (this.alerts.length >= CaseService.MAX_ALERTS) return null;

    const template = this.alerts[Math.floor(Math.random() * this.alerts.length)];
    if (!template) return null;

    const id = `A-${this.generatedAlertCounter++}`;
    const sourceIp = this.#randomIp();
    const now = new Date();
    const clonedEvents = template.logs.map((log, index) => ({
      ...log,
      timestamp: new Date(now.getTime() + index * 9000).toISOString(),
      source_ip: sourceIp,
      user: this.#randomUser(),
      raw_log: log.raw_log.replace(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g, sourceIp),
    }));

    const alert = {
      ...template,
      alert_id: id,
      description: `${template.description} Generated by live simulation.`,
      logs: clonedEvents,
    };

    const incident = {
      incident_id: `INC-${id.slice(2)}`,
      title: template.name,
      severity: template.severity,
      status: 'New',
      community: this.#randomCommunity(),
      assigned_to: 'Unassigned',
      created_date: now.toISOString(),
      alert_ids: [id],
      escalated: false,
    };

    this.alerts.unshift(alert);
    this.incidents.unshift(incident);
    this.liveFeed.unshift(this.#feedItemFromAlert(alert));
    this.liveFeed = this.liveFeed.slice(0, 18);
    this.notify();
    return { alert, incident };
  }

  #alertWithRule(alert) {
    if (!alert) return null;
    const rule = this.rules.find((item) => item.rule_id === alert.rule_id);
    return {
      ...alert,
      rule: rule?.summary || 'Rule definition not found.',
      yara_rule: rule?.rule_code || '',
      rule_name: rule?.name || '',
    };
  }

  getDashboardStats() {
    const incidents = this.getIncidents();
    const active = incidents.filter((incident) => incident.status !== 'Closed');
    const closedCases = this.cases.filter((caseItem) => caseItem.status === 'Closed' && caseItem.closed_at);

    return {
      activeIncidents: active.length,
      threatsDetected: this.alerts.length,
      assetsProtected: 12847,
      mttr: this.#calculateMttr(closedCases),
    };
  }

  getLiveFeed() {
    return [...this.liveFeed];
  }

  getTrendData(range) {
    const data = {
      '24H': [2, 4, 3, 7, 5, 9, 6, 8, 10, 7, 12, 9],
      '7D': [18, 26, 22, 31, 29, 36, 33],
      '30D': [64, 58, 73, 80, 71, 96, 88, 91, 105, 99],
    };
    return data[range] || data['24H'];
  }

  getWorkload() {
    const activeCases = this.cases.filter((caseItem) => caseItem.status !== 'Closed').length;
    const unassigned = this.getIncidents().filter((incident) => incident.assigned_to === 'Unassigned').length;
    const highSeverity = this.getIncidents().filter((incident) => incident.severity === 'High' && incident.status !== 'Closed').length;

    return { activeCases, unassigned, highSeverity };
  }

  async #loadJson(url, fallback) {
    if (!url) return fallback;
    const response = await fetch(url, { cache: 'no-store' });
    if (!response.ok) throw new Error(`Failed to load ${url}`);
    return response.json();
  }

  #incidentWithRuntimeFields(incident) {
    const linkedCase = this.getCaseByIncident(incident.incident_id);
    return {
      ...incident,
      status: linkedCase?.status || incident.status,
      case_id: linkedCase?.case_id || '',
    };
  }

  #buildInitialFeed() {
    return this.alerts.map((alert) => this.#feedItemFromAlert(alert));
  }

  #feedItemFromAlert(alert) {
    const firstLog = alert.logs?.[0] || {};
    return {
      ip: firstLog.source_ip || '0.0.0.0',
      event_type: alert.name,
      description: alert.description,
      timestamp: firstLog.timestamp || new Date().toISOString(),
    };
  }

  #calculateMttr(closedCases) {
    if (!closedCases.length) return '18m';

    const minutes = closedCases
      .map((caseItem) => {
        const start = new Date(caseItem.created_at).getTime();
        const end = new Date(caseItem.closed_at).getTime();
        return Number.isFinite(start) && Number.isFinite(end) ? (end - start) / 60000 : 0;
      })
      .filter((value) => value > 0);

    if (!minutes.length) return '18m';
    return `${Math.round(minutes.reduce((sum, value) => sum + value, 0) / minutes.length)}m`;
  }

  #randomIp() {
    const ranges = ['10.40.18', '172.16.22', '192.168.70', '203.0.113'];
    return `${ranges[Math.floor(Math.random() * ranges.length)]}.${Math.floor(Math.random() * 220) + 20}`;
  }

  #randomUser() {
    const users = ['jdelacruz', 'admin', 'msantos', 'rreyes', 'svc-backup'];
    return users[Math.floor(Math.random() * users.length)];
  }

  #randomCommunity() {
    const communities = ['PUPT', 'PUP-STA MESA', 'PUPSJ'];
    return communities[Math.floor(Math.random() * communities.length)];
  }
}
